Generate opam file with Dune
ocaml/opam-file-format pull request #62
Opened 2024-12-14 00:31 UTC by smorimoto

- Generate opam file with Dune
- Update menhir extension to 3.0

2024-12-14 01:04 UTC, kit-ty-kate requested changes
What is the reasoning behind this change?
Imo this gives us more work for no improvements, worse the generated file has superfluous steps and can sometimes be buggy. I'm personally wholly against it.

2024-12-14 01:17 UTC, smorimoto commented
I was trying to enable some flags by bumping to Menhir extension 3.0. We could just enable it.

2024-12-14 11:36 UTC, kit-ty-kate commented
> I was trying to enable some flags by bumping to Menhir extension 3.0. We could just enable it.

Looking into it, it seems that it only brings the `(explain ...)` field. I personally see little use to enable it all the time. I don't think it makes it worth bumping the minimum required version of dune just for something developers would use. This can very well stay a local change without forcing everyone using opam-file-format (including distributions that do not have dune 3.17) to upgrade to dune 3.17

2025-09-12 22:42 UTC, kit-ty-kate commented
I'll close this on the basis of my previous comments. Thanks for the suggestion though!

2025-09-12 22:42 UTC, closed without merging